### ISSUE TITLE
引用错误

### ISSUE THREAD

**Issue by xumengzi** [f2e-awesome/knowledge#16]
![image](https://user-images.githubusercontent.com/15715076/98782883-b3003780-2433-11eb-85b5-1069cc8a55eb.png)

这篇文章作者的学习css文章系列, 第四篇, 并不是css4
烦请更正

**Comment by chenfengyanyu** [comment]
感谢指出，已更正



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xumeng <notifications@github.com&gt;
发送时间: 2020年11月11日 15:38
收件人: f2e-awesome/knowledge <knowledge@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[f2e-awesome/knowledge] 引用错误 (#16)





 

 
这篇文章作者的学习css文章系列, 第四篇, 并不是css4
 烦请更正
